### ISSUE TITLE
Log out issue

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#13]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMDI3YzBmNTctNzg5YS00YTBmLWIxZGQtM2I1NzE2Nzg4MTgzIiwiZGVwbG95X2lkIjoiNjQ2YjlkNjhkMjJjMzAwMDA4NWU3OWQ2IiwiaWQiOiI5MzYyY2M4NS1kMzk3LTQ4MjEtODMzNS1kMjVmN2Y1MTNmNjUifQ==)

### Description of issue
log out button is not working properly. 

### Expected result
I log out the website next I click the profile button didn't show the user details.

### Actual result
I log out the website but I click the profile button that page show my details.

### Steps to reproduce
1. Go to the home page.
2. Click the Log Out Button.
3. Click the profile button.

```
Path:      /pages/home/profile.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Fhome%2Fprofile.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/home/profile.html)

**Comment by mathangn** [comment]
I cleared this bug. can you please check and if have any issues let me know.

**Comment by Parameshwari2004** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
