### ISSUE TITLE
Wishlist issue

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#14]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMDI3YzBmNTctNzg5YS00YTBmLWIxZGQtM2I1NzE2Nzg4MTgzIiwiZGVwbG95X2lkIjoiNjQ2YjlkNjhkMjJjMzAwMDA4NWU3OWQ2IiwiaWQiOiJmYzQzN2M0Zi1iY2M3LTRjOTktYjE1Zi0xMzgyMTkwOWZhNTUifQ==)

### Description of issue
Wishlist button is not working correctly.

### Expected result
I click one product that product only save the Wishlist.

### Actual result
I click one product in the second row but it as two products add  in the Wishlist.

### Steps to reproduce
1. Go to the product page.
2. Click the Wishlist icon in the second row.
3. Click one product.

```
Path:      /pages/stores/prducts/nike.html?value=0
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Fstores%2Fprducts%2Fnike.html%3Fvalue%3D0&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/stores/prducts/nike.html?value=0)

**Comment by mathangn** [comment]
I cleared this bug. can you please check and if have any issues let me know.

**Comment by Parameshwari2004** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
