### ISSUE TITLE
Buying Product working in without login

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#16]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMDI3YzBmNTctNzg5YS00YTBmLWIxZGQtM2I1NzE2Nzg4MTgzIiwiZGVwbG95X2lkIjoiNjQ2YjlkNjhkMjJjMzAwMDA4NWU3OWQ2IiwiaWQiOiIxMmNhZjMwNy05Nzg0LTQ2ODktYjQ2Ni0zNWE4NTU2ZjQ1Y2YifQ==)

### Description of issue
Buy now button is working in without login.

### Expected result
User buy the product only after login.

### Actual result
I logout the website but I buy the product without login.

### Steps to reproduce
1. Click the logout button.
2. Go to the product page buy one product.

```
Path:      /pages/cart/payment-page.html?id=2
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Fcart%2Fpayment-page.html%3Fid%3D2&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/cart/payment-page.html?id=2)

**Comment by mathangn** [comment]
I cleared this bug. can you please check and if have any issues let me know.

**Comment by Parameshwari2004** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
