### ISSUE TITLE
Email bug

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#2]
### Description of issue
Email pattern is not working properly.

### Expected result
Email pattern should work properly.

### Actual result
Email pattern is not working properly.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/login/signup.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Flogin%2Fsignup.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/login/signup.html)

**Comment by Parameshwari2004** [comment]
It is worked properly

**Comment by mathangn** [comment]
Issue cleared
