### ISSUE TITLE
Update store button issue

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#5]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMDI3YzBmNTctNzg5YS00YTBmLWIxZGQtM2I1NzE2Nzg4MTgzIiwiZGVwbG95X2lkIjoiNjQzNmFkOGM5OWFjMTEwMDA3MmFiM2FhIiwiaWQiOiIyYjFjN2VmYy04N2I2LTQzZjktOGRlMS1mM2M5NGFmYzFmNmYifQ==)

### Description of issue
In the admin store form I edited one store and I clicked update button. that values for updated but else also working. that is issue.

### Expected result
It's will work if only don't work else that alert.

### Actual result
It's working else also. This button is not working properly.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/admin/create_store.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Fadmin%2Fcreate_store.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/admin/create_store.html)

**Comment by mathangn** [comment]
I cleared this bug. can you please check and if have any issues let me know.

**Comment by Parameshwari2004** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
