### ISSUE TITLE
Profile Page Update Button

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#7]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMDI3YzBmNTctNzg5YS00YTBmLWIxZGQtM2I1NzE2Nzg4MTgzIiwiZGVwbG95X2lkIjoiNjQzZjY1MDI3M2U4NzQwMDA4NjAwY2MwIiwiaWQiOiJhYmU1OTRjMy00NmQ1LTRjNTAtYjYzYy02YTEyOTgyYzJmMTUifQ==)

### Description of issue
Profile page update button is not working in the country and state.

### Expected result
If the user edit the profile it show all the details.

### Actual result
In profile page after editing address and after clicking edit button the country and state input field getting disabled. 

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/home/profile.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Fhome%2Fprofile.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/home/profile.html)

**Comment by mathangn** [comment]
I cleared this bug. can you please check and if have any issues let me know.
