### ISSUE TITLE
Wrong navigation issue.

### ISSUE THREAD

**Issue by Parameshwari2004** [fssa-batch3/mathankumar.nagarajan__web_project#8]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMDI3YzBmNTctNzg5YS00YTBmLWIxZGQtM2I1NzE2Nzg4MTgzIiwiZGVwbG95X2lkIjoiNjQ1MGQ0ZTM0YjRmYjAwMDA4ODQxM2M2IiwiaWQiOiJiZTMwM2JkYi02MzhiLTQxNDYtYWFmMi1kZjQ1ZjE0YWQzY2IifQ==)

### Description of issue
Wrong navigation issue.

### Expected result
I should navigate to signup when i click the signup button

### Actual result

but I was navigated to signin page when I click the signup button
### Steps to reproduce
1. go to home page
2. click the signup button
3. check the page

```
Path:      /pages/login/login.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--spartans-market-town.netlify.app%2Fpages%2Flogin%2Flogin.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--spartans-market-town.netlify.app/pages/login/login.html)

**Comment by mathangn** [comment]
I cleared this bug. can you please check and if have any issues let me know.

**Comment by Parameshwari2004** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
